name: Build and Deploy Vite React App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./pgs-website

      - name: Build Vite app
        run: npm run build
        working-directory: ./pgs-website

      - name: Deploy to Nginx directory
        run: |
          echo "Removing old dist..."
          rm -rf /var/www/html/pgs_website/Pioneer-Girls-School/pgs-website/dist
          echo "Copying new dist..."
          cp -r pgs-website/dist /var/www/html/pgs_website/Pioneer-Girls-School/pgs-website/
          echo "Deployed successfully."

      - name: Restart Nginx (if needed)
        run: sudo systemctl reload nginx
